# Generated by Django 5.0.3 on 2024-03-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0002_alter_parkingslot_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
